version: '3.1'

services:

  aws:
    image: localstack/localstack
    container_name: awslocal
    hostname: localstack
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=ap-northeast-2
    ports:
      - 4566:4566
    volumes:
      - ./aws:/docker-entrypoint-initaws.d

  rdbms:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
